# This is a basic workflow to help you get started with Actions

name: Terraform-githubaction

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: environment
        options:
        - production
        - development
        - testing

jobs:
  Terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
     AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_key }}
     
    defaults:
     run:
      working-directory: Terraform/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
         echo ${{ github.workspace }}
         echo $GITHUB_WORKSPACE
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          
      - name: Terraform init
        id: init
        run: terraform init
        
      - name: Terraform plan -var workspacePath=${{github.workspace}}
        id: plan
        run: terraform plan
        
      - name: Terraform apply -var workspacePath=${{github.workspace}}
        id: apply
        run: terraform apply -auto-approve
